/**
 * @param {number[]} heights
 * @return {number}
 */
var heightChecker = function(heights) {
    // CHECK FOR CONSTRAINTS -- HEIGHTS LENGTH IS LESS THAN 100 
    // HEIGHT ITSELF IS LESS THAN 100
    // SORT THE ARRAY IN INCREASING ORDER WITHOUT MOVING ELEMENTS THAT ARE IN THE RIGHT ORDER
    // CREATE COUNTER TO KEEP TRACK OF EVERY STUDENT THAT MOVES
    // FOR EVERY STUDENT THAT MOVES, COUNTER GOES UP 
};